/*
 * Copyright (c) 2013-2022 kopiLeft Services SARL, Tunis TN
 * Copyright (c) 1990-2022 kopiRight Managed Solutions GmbH, Wien AT
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License version 2.1 as published by the Free Software Foundation.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */
package org.kopi.galite.visual

import java.awt.event.InputEvent
import java.awt.event.KeyEvent

import org.jetbrains.annotations.TestOnly
import org.kopi.galite.visual.dsl.form.Key
import org.kopi.galite.visual.base.UComponent
import org.kopi.galite.visual.dsl.common.LocalizableElement
import org.kopi.galite.visual.dsl.common.LocalizationWriter
import org.kopi.galite.visual.dsl.common.Menu
import org.kopi.galite.visual.l10n.LocalizationManager

/**
 * This class represents an actor, ie a menu element with a name and may be an icon, a shortcut
 * and a help
 *
 * An Actor is an item to be linked to a command, if its [icon] is specified, it will appear
 * in the icon_toolbar located under the menu bar, otherwise, it will only be accessible from the menu bar
 *
 * @param menu                the containing menu
 * @param label               the label
 * @param help                the help text
 * @param source              path localization file
 */
open class Actor(val menu: Menu,
                 val label: String,
                 var help: String?,
                 ident: String? = null,
                 source: String? = null)
  : VModel, LocalizableElement(ident, source) {

  // The shortcut key
  var key: Key? = null
    set(key) {
      checkKey(key)
      field = key
    }

  // The actor icon
  var icon: Icon? = null
    set(value) {
      iconName = value?.iconName
      field = value
    }

  // --------------------------------------------------------------------
  // INTERNAL DATA MEMBERS
  // --------------------------------------------------------------------
  internal var menuName: String = menu.label
  internal var menuItem: String? = label
  internal var number = 0 // The number for the actor
  internal var iconName: String? = null
  internal var action: (() -> Unit)? = null
  private var display: UActor? = null
  internal var handler: ActionHandler? = null // the handler for the actor

  internal val menuIdent: String = menu.label
  private val menuSource = menu.sourceFile
  internal var acceleratorKey: Int = 0
  internal var acceleratorModifier: Int = 0
  internal var userActor: Boolean = true

  /**
   * See kdoc of [Actor]
   *
   * @param menuIdent           the qualified name of menu source file which this actor belongs to
   * @param menuSource          the menu source qualified name
   * @param actorIdent          the qualified name of actor's source file
   * @param actorSource         the actor source qualified name
   * @param acceleratorKey      the accelerator key description
   * @param acceleratorModifier the modifier accelerator key
   * @param userActor           True if the actor is defined by the user.
   *                            False if the actor is generated by galite and then it should be localized by
   *                            galite localization files such as "org/kopi/galite/visual/General"
   */
  constructor(menuIdent: String,
              menuSource: String?,
              actorIdent: String,
              actorSource: String?,
              iconName: String?,
              acceleratorKey: Int,
              acceleratorModifier: Int,
              userActor: Boolean = false)
          : this(Menu(menuIdent, menuIdent, menuSource),
                 actorIdent,
                 null,
                 actorIdent,
                 actorSource) {
    this.iconName = iconName
    this.acceleratorKey = acceleratorKey
    this.acceleratorModifier = acceleratorModifier
    this.userActor = userActor
  }

  override fun getDisplay(): UActor? = display

  override fun setDisplay(display: UComponent) {
    assert(display is UActor) { "Actor display should be UActor" }
    this.display = display as UActor
  }

  var isEnabled: Boolean
    get() = display != null && display!!.isEnabled() // Checks whether the actor is enabled
    set(enabled) {
      display?.setEnabled(enabled) // Enables/disables the actor.
    }

  // ----------------------------------------------------------------------
  // ACTIONS HANDLING
  // ----------------------------------------------------------------------
  fun performAction() {
    handler!!.performAsyncAction(object : Action("$menuItem in $menuName") {
      override fun execute() {
        handler!!.executeVoidTrigger(number)
        action?.let { it() }
      }

      /**
       * Returns `true` if this action can be cancelled in an action queue context.
       * This means that the action can be removed from an action queue when performing
       * a clear operation.
       *
       * quit a reset action cannot be cancelled. They will be executed even if the action
       * queue is cleared. Implementations should care about this.
       *
       * @return `true` if this not a reset action.
       */
      override fun isCancellable(): Boolean =
        !("quit".equals(ident, ignoreCase = true) || "break".equals(ident, ignoreCase = true))
    })
  }

  fun performBasicAction() {
    handler!!.executeVoidTrigger(number)
    action?.invoke()
  }

  // ----------------------------------------------------------------------
  // HASHCODE AND EQUALS REDEFINITION
  // ----------------------------------------------------------------------
  override fun hashCode(): Int = ident.hashCode() * ident.hashCode()

  override fun equals(other: Any?): Boolean {
    return if (other !is Actor) {
      false
    } else {
      menuName == other.menuName
              && menuItem == other.menuItem
              && ((iconName == null && other.iconName == null)
              || (iconName != null
              && other.iconName != null
              && iconName == other.iconName))
    }
  }

  // ----------------------------------------------------------------------
  // LOCALIZATION
  // ----------------------------------------------------------------------
  /**
   * Localizes this actor
   *
   * @param     manager         the manger to use for localization
   */
  fun localize(manager: LocalizationManager) {
    val menuLoc = manager.getMenuLocalizer(menuSource, menuIdent)
    val actorLoc = manager.getActorLocalizer(sourceFile, ident)
    menuName = menuLoc.getLabel()
    menuItem = actorLoc.getLabel()
    help = actorLoc.getHelp()
  }

  // ----------------------------------------------------------------------
  // HELP HANDLING
  // ----------------------------------------------------------------------
  fun helpOnCommand(help: VHelpGenerator) {
    help.helpOnCommand(menuName,
                       menuItem,
                       iconName,
                       acceleratorKey,
                       acceleratorModifier,
                       this.help)
  }

  // --------------------------------------------------------------------
  // DEBUG
  // --------------------------------------------------------------------
  override fun toString(): String {
    val buffer = StringBuffer()

    buffer.append("Actor[")
    buffer.append("menu=$menuName:$menuItem")
    if (iconName != null) {
      buffer.append(", ")
      buffer.append("icon=$iconName")
    }
    if (acceleratorKey != 0) {
      buffer.append(", ")
      buffer.append("key=$acceleratorKey:$acceleratorModifier")
    }
    buffer.append(", ")
    buffer.append("help=$help")
    buffer.append("]")
    return buffer.toString()
  }

  val _actorSource @TestOnly get() = sourceFile
  val _menuSource @TestOnly get() = menuSource
  val _menuIdent @TestOnly get() = menuIdent
  val _iconName @TestOnly get() = iconName
  val _acceleratorKey @TestOnly get() = acceleratorKey
  val _menuName @TestOnly get() = menuName
  val _number @TestOnly get() = number

  fun checkKey(key: Key?) {
    if (key == null) {
      acceleratorModifier = 0
      acceleratorKey = KeyEvent.VK_UNDEFINED
    } else {
      acceleratorKey = key.value
      acceleratorModifier = if (key.toString().contains("SHIFT_")) InputEvent.SHIFT_MASK else 0
    }
  }

  // ----------------------------------------------------------------------
  // XML LOCALIZATION GENERATION
  // ----------------------------------------------------------------------
  fun genLocalization(writer: LocalizationWriter) {
    writer.genActorDefinition(ident, label, help)
  }
}

enum class Icon(val iconName: String) {
  ALL("all"),
  BLOCK("block"),
  BORDER("border"),
  BREAD_CRUMB_SEPARATOR("bread_crumb_separator"),
  BREAK("break"),
  CALENDAR("calendar"),
  COLLAPSED("collapsed"),
  COLLAPSED_P("collapsed_p"),
  COPY("copy"),
  DELETE("delete"),
  DESK("desk"),
  DETAIL("detail"),
  DETAIL_VIEW("detail_view"),
  DOWN("down"),
  DUKE("duke"),
  EDIT("edit"),
  EXPANDED_A("expanded_a"),
  EXPANDED("expanded"),
  EXPANDED_P("expanded_p"),
  EXPORT_CSV("exportCsv"),
  EXPORT_PDF("exportPdf"),
  EXPORT_XLSX("exportXlsx"),
  FOLD_COLUMN("foldColumn"),
  FOLD("fold"),
  FORMULA("formula"),
  HELP("help"),
  HOME("home"),
  INSERT_LINE("insertline"),
  INSERT("insert"),
  LIST("list"),
  LOADING("loading"),
  LOGIN_IMG("login_img"),
  MAIL("mail"),
  MENU_QUERY("menuquery"),
  NOTE("note"),
  NOTHING("nothing"),
  OPEN("open"),
  OPTIONS("options"),
  PREVIEW("preview"),
  PRINT("print"),
  QUIT("quit"),
  SAVE("save"),
  SEARCH_OP("searchop"),
  SEARCH("search"),
  SERIAL_QUERY("serialquery"),
  SERVICE_OFF("serviceoff"),
  SERVICE_ON("serviceon"),
  STORE("store"),
  SUGGEST("suggest"),
  TIMESTAMP("timeStamp"),
  TRI("tri"),
  UNFOLD_COLUMN("unfoldColumn"),
  UNFOLD("unfold"),
  UP("up"),
  ADD("add"),
  ALIGN_CENTER("align_center"),
  ALIGN_JUSTIFY("align_justify"),
  ALIGN_LEFT("align_left"),
  ALIGN_RIGHT("align_right"),
  APPLY("apply"),
  AREA_CHART("area_chart"),
  ARROW_FIRST("arrowfirst"),
  ARROW_LAST("arrowlast"),
  ARROW_LEFT("arrowleft"),
  ARROW_RIGHT("arrowright"),
  ARTICLE("article"),
  ASK("ask"),
  BAR_CHART("bar_chart"),
  BKUP3("bkup3"),
  BKUP("bkup"),
  BLOCK2("block2"),
  BOARD("board"),
  BOLD("bold"),
  BOMB("bomb"),
  BOOKMARK("bookmark"),
  BOX_ARROW("boxarrow"),
  BW("bw"),
  CALCULATE("calculate"),
  CFOLDER("cfolder"),
  CHART_VIEW("chart_view"),
  CHECKBOX("checkbox"),
  CLIP("clip"),
  COLLAPSE_DB("collapsedb"),
  COLLAPSED_F("collapsed_f"),
  COLLAPSED_T("collapsed_t"),
  COLUMN_CHART("column_chart"),
  COMBO("combo"),
  CONFIG("config"),
  CONVERT("convert"),
  CUT("cut"),
  DELETE_LINE("deleteline"),
  DONE("done"),
  ERROR("error"),
  EXPANDED_B("expandedb"),
  EXPANDED_F("expanded_f"),
  EXPANDED_S("expanded_s"),
  EXPANDED_T("expanded_t"),
  EXPORT("export"),
  FAX("fax"),
  FW("fw"),
  GIF_ICON("gifIcon"),
  GREEN("green"),
  GUIDE("guide"),
  IDENT("ident"),
  INDEX("index"),
  INTERRUPT("interrupt"),
  ITALIC("italic"),
  JPG_ICON("jpgIcon"),
  LAUNCH("launch"),
  LINE_CHART("line_chart"),
  LOCK("lock"),
  LOGIN("login"),
  MONEY_CHECK("moneycheck"),
  MONEY("money"),
  NOTICE("notice"),
  OFOLDER("ofolder"),
  PAGE_FIRST("pageFirst"),
  PAGE_LAST("pageLast"),
  PAGE_LEFT("pageLeft"),
  PAGE_RIGHT("pageRight"),
  PASSWORD("password"),
  PASTE("paste"),
  PHONE("phone"),
  PIE_CHART("pie_chart"),
  PRINT_OPTIONS("printoptions"),
  PROJECT("project"),
  RED("red"),
  REDO("redo"),
  REFRESH("refresh"),
  RELOAD("reload"),
  REPORT("report"),
  SEC("sec"),
  SELECTED("selected"),
  SEND("send"),
  SORT("sort"),
  SPLIT("split"),
  STANDARD("standard"),
  STICK("stick"),
  STOP("stop"),
  TODO("todo"),
  TOP("top"),
  UNDERLINE("underline"),
  UNDO("undo"),
  UNIDENT("unident"),
  UNSTICK("unstick"),
  UPDATE("update"),
  USERS("users"),
  UTILS("utils"),
  VALIDATE("validate"),
  WAIT("wait"),
  WARNING("warning"),
  WINDOW("window"),
  YELLOW("yellow"),
  ZOOM_HEIGHT("zoomheight"),
  ZOOM_MINUS("zoomminus"),
  ZOOM_OPTIMAL("zoomoptimal"),
  ZOOM_PLUS("zoomplus"),
  ZOOM_WIDTH("zoomwidth")
}
