// Generated by msggen from CompilerMessages.xml
package org.kopi.compiler.base

import org.kopi.galite.util.base.MessageDescription

interface CompilerMessages {
  companion object {
    val FORMATTED_ERROR: MessageDescription = MessageDescription("{0}", null, 0)
    val FORMATTED_CAUTION: MessageDescription = MessageDescription("{0}", null, 1)
    val FORMATTED_WARNING: MessageDescription = MessageDescription("{0}", null, 2)
    val FORMATTED_NOTICE: MessageDescription = MessageDescription("{0}", null, 3)
    val FORMATTED_INFO: MessageDescription = MessageDescription("{0}", null, 4)
    val NO_INPUT_FILE: MessageDescription = MessageDescription("No input file given", null, 0)
    val FILE_NOT_FOUND: MessageDescription = MessageDescription("File \"{0}\" not found", null, 0)
    val IO_EXCEPTION: MessageDescription = MessageDescription("I/O Exception on file \"{0}\": {1}", null, 0)
    val UNSUPPORTED_ENCODING: MessageDescription = MessageDescription("Character encoding \"{0}\" is not supported on this platform", null, 0)
    val CANNOT_CREATE: MessageDescription = MessageDescription("Cannot create file \"{0}\"", null, 0)
    val INVALID_LIST_FILE: MessageDescription = MessageDescription("Invalid list file \"{0}\" : {1}", null, 0)
    val NO_VIABLE_ALT_FOR_CHAR: MessageDescription = MessageDescription("Unexpected char \"{0}\"", null, 0)
    val UNEXPECTED_EOF: MessageDescription = MessageDescription("Unexpected end of file", null, 0)
    val EOF_IN_TRADITIONAL_COMMENT: MessageDescription = MessageDescription("End of file in comment", null, 0)
    val EOF_IN_ENDOFLINE_COMMENT: MessageDescription = MessageDescription("End of file in comment", null, 1)
    val ILLEGAL_CHAR: MessageDescription = MessageDescription("Unexpected char \"{0}\"", null, 0)
    val BAD_ESCAPE_SEQUENCE: MessageDescription = MessageDescription("Illegal escape sequence \"{0}\"", null, 0)
    val BAD_END_OF_LINE: MessageDescription = MessageDescription("Unexpected end of line in {0}", null, 0)
    val SYNTAX_ERROR: MessageDescription = MessageDescription("Syntax error: {0}", null, 0)
    val COMPILATION_STARTED: MessageDescription = MessageDescription("[ start compilation in verbose mode ]", null, 4)
    val FILE_PARSED: MessageDescription = MessageDescription("[ parsed {0} in {1} ms ]", null, 4)
    val INTERFACES_CHECKED: MessageDescription = MessageDescription("[ checked interfaces in {0} ms ]", null, 4)
    val BODY_CHECKED: MessageDescription = MessageDescription("[ checked body of {0} in {1} ms ]", null, 4)
    val CONDITION_CHECKED: MessageDescription = MessageDescription("[ checked condition of {0} in {1} ms ]", null, 4)
    val CLASSFILE_GENERATED: MessageDescription = MessageDescription("[ optimized and generated {0} in {1} ms ]", null, 4)
    val JAVA_CODE_GENERATED: MessageDescription = MessageDescription("[ generated {0} ]", null, 4)
    val CLASS_LOADED: MessageDescription = MessageDescription("[ loaded {0} ]", null, 4)
    val COMPILATION_ENDED: MessageDescription = MessageDescription("[ compilation ended ]", null, 4)
  }
}