// Generated by optgen from ApplicationOptions.xml
package org.kopi.vkopi.lib.ui.swing.visual;

import gnu.getopt.Getopt;
import gnu.getopt.LongOpt;

public class ApplicationOptions extends org.kopi.galite.db.ConnectionOptions {

  public ApplicationOptions(String name) {
    super(name);
  }

  public ApplicationOptions() {
    this("Application");
  }

  public String form = null;
  public String locale = null;
  public boolean nobugreport = false;

  public boolean processOption(int code, Getopt g) {
    switch (code) {
    case 'f':
      form = getString(g, ""); return true;
    case 'l':
      locale = getString(g, ""); return true;
    case 'r':
      nobugreport = !false; return true;
    default:
      return super.processOption(code, g);
    }
  }

  public String[] getOptions() {
    String[]	parent = super.getOptions();
    String[]	total = new String[parent.length + 3];
    System.arraycopy(parent, 0, total, 0, parent.length);
    total[parent.length + 0] = "  --form, -f<String>:   The initial form to run";
    total[parent.length + 1] = "  --locale, -l<String>: The localization to use when the user's locale is not supported";
    total[parent.length + 2] = "  --nobugreport, -r:    disable reporting trouble. [false]";
    
    return total;
  }


  public String getShortOptions() {
    return "f:l:r" + super.getShortOptions();
  }


  public void version() {
    System.out.println("Version 2.3B released 17 September 2007");
  }


  public void usage() {
    System.err.println("usage: Application [option]*");
  }

  public LongOpt[] getLongOptions() {
    LongOpt[]	parent = super.getLongOptions();
    LongOpt[]	total = new LongOpt[parent.length + LONGOPTS.length];
    
    System.arraycopy(parent, 0, total, 0, parent.length);
    System.arraycopy(LONGOPTS, 0, total, parent.length, LONGOPTS.length);
    
    return total;
  }

  private static final LongOpt[] LONGOPTS = {
    new LongOpt("form", LongOpt.REQUIRED_ARGUMENT, null, 'f'),
    new LongOpt("locale", LongOpt.REQUIRED_ARGUMENT, null, 'l'),
    new LongOpt("nobugreport", LongOpt.NO_ARGUMENT, null, 'r')
  };
}
