// Generated by msggen from OptgenMessages.xml
package org.kopi.galite.util.optionGenerator.utils

import org.kopi.compiler.base.CompilerMessages
import org.kopi.galite.util.base.MessageDescription

interface OptgenMessages : CompilerMessages {
  companion object {
    val DUPLICATE_DEFINITION: MessageDescription =
      MessageDescription("Option \"{0}\" redefined in \"{1}\": previous definition in \"{2}\"", null, 0)
    val DUPLICATE_SHORTCUT: MessageDescription =
      MessageDescription("Shortcut \"{0}\" redefined in \"{1}\": previous definition in \"{2}\"", null, 0)
  }
}