
=== Generalities

==== Predefined Field Types

Every form or report field in Galite have field type that can be one of the 11 ready to use predefined types :

[source,kotlin]
----
- DECIMAL                       // used to insert decimal values
- IMAGE                         // used to insert images
- INT                           // used to insert integer values
- TEXT                          // used to insert text values
- STRING                        // used to insert string values
- DATETIME                      // used to insert a datetime value
- BOOL                          // used to insert a true or false value
- MONTH                         // used to insert years months value
- TIME                          // used to insert a hours:minutes time value
- TIMESTAMP                     // used to insert a timestamp value
- WEEK                          // used to insert years weeks  value
----

===== The STRING Field Type

A STRING is used to enter characters which can be either letters, numbers or both. The width has always to be given. Moreover, you can optionally indicate how many rows it will contain and how many will finally be displayed on the form. If these optional arguments are used, you have to indicate the carriage return method by specifying either the FIXED ON or the FIXED OFF option. +
There are also three other options you can use in order to modify the String's case :

- Convert.NAME  (Converts the first letter of each word to capital letter)
- Convert.UPPER (Convert the whole text to capital letters)
- Convert.LOWER (Converts the whole text to normal letters)

*Syntax:*

[source,kotlin]
----

StringType   :
STRING(
    width: Int,
    height: Int,
    visibleHeight: Int,
    [FixOption: Fixed,]
    [StringFormat: Convert,]
    [styled: Boolean]
)

FixOption    : Fixed.ON
               Fixed.OFF

StringFormat : Convert.UPPER
               Convert.LOWER
               Convert.NAME

styled      :  true   // present rich text
               false  // present text area
----

*Example*

[source,kotlin]
----
val name = visit(domain = STRING(40, 10, 4, Fixed.ON, Convert.UPPER), position = at(1, 1)) {
    label = "Description"
    help = "A description"
}

// For better readability it's recommended to specify the parameters names:
STRING(width = 40, height = 10, visibleHeight = 4, fixed = Fixed.ON, convert = Convert.UPPER)
----

In this example, the text inserted will contain up to 40 characters and up to 10 rows. However, only the first 4 rows will be displayed on the form. Moreover, All the letters in the text will be converted to capital letters.

===== The TEXT Field Type

A Text and a String are similar apart from the fact that in a text, two parameters have always to be given: namely the width and the height of the field whereas you only need to determine the width in a string. +
For example, you can write `STRING(40, 10, 4)` or `STRING(40)` but you have to write `TEXT(40, 10)` or `TEXT(40, 10, 4)`.


*Syntax:*

[source,java]
----
TextType      :
TEXT(width: Integer ,height: Integer ,visible: Integer, [FixOption])

[FixOption]   : FIXED.ON
                FIXED.OFF
----

*Example*

[source,kotlin]
----
val informations = visit(domain = STRING(80, 50, 10, Fixed.ON, styled = true), position = at(3, 1)) {
    label = "Richtext"
    help = "A Richtext editor"
}
----

In this example, the text inserted will contain up to 80 characters and up to 50 rows. However, only the first 10 rows. +
The field is a richtext editor beacause the option `styled` is set to true.

===== The IMAGE Field Type

This field type is used to insert an illustration or a picture. When introducing an IMAGE, you have to determine its width and height. These values have to be integers and are measured in pixel. In this case, the two attributes are compulsory. The field will look like a file chooser that lets you choose an image file to show in the field.

*Syntax:*

[source,kotlin]
----
ImageType :
IMAGE(width: Int, height: Int)
----

*Example:*

[source,kotlin]
----
val image = visit(domain = IMAGE(width = 20, height = 10), position = at(1, 3)) {
    label = "image"
    help = "The product image"
}
----
In this field, the image will have a width of 20 pixel and a height of 10 pixel.

===== The DECIMAL Field Type

A DECIMAL is used to insert numbers, integers, decimal numbers.
The maximal width has to be determined for all them.
The maximal scale i.e the number of characters standing after the comma has also to be defined.
Also the comma has to be counted as a character.
You can also set the minimum and the maximum values for the DECIMAL field with the optional parameters minValue and maxValue.

*Syntax:*

[source,kotlin]
----
DecimalType   :
DECIMAL(width: Int, scale: Int) {
    [minValue = 'A decimal value']
    [maxValue = 'A decimal value']
}
----

*Example:*

[source,kotlin]
----
val price = visit(domain = DECIMAL(width = 10, scale = 5), position = at(1, 1)) {
    label = "price"
    help = "The price"
    minValue = Decimal.valueOf("1.9")
    maxValue = Decimal.valueOf("5.9")
}
----

===== The INTEGER Field Type

Integer field type is INT is used to insert integers. Only the text width is to be defined. The minValue and maxValue options are also available for this type.

*Syntax:*

[source,kotlin]
----
IntegerType:
INT(width: Int) {
    [minValue = 'An integer value']
    [maxValue = 'An integer value']
}
----

*Example*

[source,kotlin]
----
val count = visit(domain = INT(3), position = follow(name)) {
    label = "Cars"
    help = "The number of cars"
    minValue = 1
    maxValue = 130
}
----

==== Code Field Types

In addition to the predefined field types already available in Galite, you can define more specific types like CODE type.

===== The CODE types

The code Filed can be defined with many types like Boolean, Int, Decimal, etc... These types enable you to have a list of item-value pairs, the items will be displayed in the field and the values will be assigned instead.

*  *The Type CODE BOOL*

In a CODE BOOL or BOOLEAN you have to assign a Boolean value to the item you have entered. Boolean values are values like "True" or "False" and "Yes" or "No".

*Syntax:*

[source,kotlin]
----
CodeBooleanType :
object "NameToUse" : CodeDomain<Boolean>() {
    init {
        CodeBooleanList
    }
}

CodeBooleanList : CodeBoolean  [CodeBooleanList]

CodeBoolean     : code : String "keyOf" value : Boolean
----

*Example*

[source,kotlin]
----
object Situation: CodeDomain<Boolean>() {
  init {
    "married" keyOf true
    "single" keyOf false
  }
}

----

* *The Type CODE INT*

In a CODE INT, you assign to each String item you have entered a INT value.

*Syntax:*

[source,kotlin]
----
CodeIntegerType :
object "NameToUse" : CodeDomain<Int>() {
    init {
        CodeIntegerList
    }
}

CodeIntegerList : CodeInteger  [CodeIntegerList]

CodeInteger     : code : String "keyOf" value : Int
----

*Example*

[source,kotlin]
----
object Days: CodeDomain<Int>() {
  init {
    "Sunday" keyOf 1
    "Monday" keyOf 2
    "Tuesday" keyOf 3
    "Wednesday" keyOf 4
    "Thursday" keyOf 5
    "Friday" keyOf 6
    "Saturday" keyOf 7
  }
}
----

* *The Type CODE DECIMAL*

In a CODE DECIMAL, each item you have entered will get a DECIMAL value, i.e integers, fixed point numbers and fraction numbers.

*Syntax:*

[source,kotlin]
----
CodeFixedType :
object "NameToUse" : CodeDomain<Decimal>() {
    init {
        CodeFixedList
    }
}

CodeFixedList : CodeFixed  [CodeFixedList]

CodeFixed     : code : String "keyOf" value : Decimal
----
*Example*

[source,kotlin]
----
object Accounting: CodeDomain<Decimal>() {
  init {
    "piece" keyOf Decimal.valueOf("1.00")
    "per cent" keyOf Decimal.valueOf("0.01")
  }
}
----

* *The Type CODE STRING*

In a CODE STRING, each item you have entered will get a STRING value, this can be useful for shortcut of long strings for example.

*Syntax:*

[source,kotlin]
----
CodeStringType :
object "NameToUse" : CodeDomain<String>() {
    init {
        CodeStringType
    }
}

CodeStringType : CodeString  [CodeStringType]

CodeString     : code : String "keyOf" value : String
----
*Example*

[source,kotlin]
----
object ProgrammingLanguage: CodeDomain<String>() {
  init {
    "JDK" keyOf "Java Development Kit"
    "JRE" keyOf "Java Runtime Environment"
  }
}
----

===== The SELECT command

As you had the possibility to call up a list or a table from the database, with the option LIST, you now can make Galite sort out information from a whole list or a table which the option SELECT and this, according to criteria you have to define. Let’s say you want to view the degrees which can be achieved in a certain year. For this, you have to use the SELECT command as you see in the following rows:

*Syntax:*

[source,kotlin]
----
List        :
class "ListName" : ListDomain<String>(20) {
    override val table = TableName

    init {
       ListColumns
    }
}

ListColumns : ListColumn  [ListColumns]

ListColumn  : SimpleName "keyOf" TableName.columnName
----

*Example*

[source,kotlin]
----
class CurrentDegree(year: Int) : ListDomain<String>(20) {
    override val table = query(
        Degree.selectAll {
            Degree.year eq year
        }
    )

    init {
        "Symbol" keyOf Degree.Symbol
        "Description" keyOf Degree.Description
    }
}
----
"Degree" is the database table to which we have to access in order to select the information.
In this example, we have used Exposed syntax to declare the select query from the Degree table, then we have created a list that contains two columns Symbol and Description those columns receive data from the result of the query.

The function `keyOf` is used in order to enter the columns in which Galite has to make its research.

As a result of your selection, you will then have a table with two columns which will contain the different sorts of degrees achievable in the year you have entered.
